version: 2
updates:
  - package-ecosystem: "maven" 
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "SageSphinx63920"
    commit-message:
      prefix: "mvn"
    labels:
      - "maven"
    open-pull-requests-limit: 3
    
  - package-ecosystem: "github-actions" 
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
