version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "SageSphinx63920"
    commit-message:
      prefix: "gradle"
    labels:
      - "gradle"
    
  - package-ecosystem: "github-actions" 
    directory: "/"
    schedule:
      interval: "weekly"
