blacklist:
  enabled: true
  allow-join-with-admin: false
  admin-permission: "blacklist.admin"
  limbo: false # Experimental
  icon-file: "icon.png" # The icon for the server if player is blacklisted. Put the file in the same folder as the config

whitelist:
  enabled: false
  change-motd: true
  hide-online-players: false # This sends fake player's AND fake player counts to the client (Currently the max players is 20-40; online 0-10; fake players cant be modified rn)

# Note: If you use a proxy you need to enable 'send-floodgate-data' on the proxy's config
# More: https://wiki.geysermc.org/floodgate/setup/
floodgate:
  prefix: "." # Prefix for the floodgate player

mariadb:
  enabled: false
  host: localhost
  port: 3306
  database: keklist
  username: root
  password: root
  options: "?useSSL=false&serverTimezone=MEZ"

messages:
  motd:
    blacklisted:
      - "<red><bold>Your IP is blacklisted on this server!"
      - "<red><bold>You are not allowed to join this server!"
    whitelisted:
      - "<orange><bold>The server is in whitelist mode but you can join."
      - "<orange><bold>Glad you can join us!"
    default:
      - "This is a normal motd"
      - "By default these are visible for everyone"

  kick:
    blacklisted:
      - "<red><bold>You're kicked because you're on the blacklist!"
      - "<red><bold>Sorry, but you're not allowed to join this server!"
    whitelisted:
      - "<orange><bold>You're kicked because the server is in whitelist mode!"
      - "<orange><bold>Sorry, but you're not on the whitelist!"