# Settings for every feature of the Keklist Paper plugin

language: "en-us" # Language for the plugin
plan-support: false # Enable support for the Plan plugin
enable-manage-command: false # Enable the /keklist command to enable/disable the blacklist/whitelist

# Settings for the blacklist feature
blacklist:
  enabled: true # Enable the blacklist feature
  allow-join-with-admin: false # Allows blacklisted player to join if a player with the admin-permission is online
  admin-permission: "blacklist.admin"
  limbo: false # Experimental; Needs velocity plugin
  icon-file: "icon.png" # The icon for the server if player is blacklisted. Put the file in the same folder as the config

# Settings for the whitelist feature
# Note: THIS WILL OVERRIDE THE DEFAULT WHITELIST; it works the same way as the default whitelist but does not import the players
whitelist:
  enabled: false # Enable the whitelist feature
  change-motd: true # Change the motd if the server is in whitelist mode
  hide-online-players: false # This sends fake player's AND fake player counts to the client
  fake-players: # List of fake players that are shown to the client NOTE: Can be empty
    - SageSphinx63920
    - hdgaymer1404Jonas
    - LPTP1
  fake-max-range: 20-40 # Please use the format: INTEGER-INTEGER
  fake-online-range: 0-10 # Please use the format: INTEGER-INTEGER

# Note: If you use a proxy you need to enable 'send-floodgate-data' on the proxy's config
# More: https://wiki.geysermc.org/floodgate/setup/
floodgate:
  prefix: "." # Prefix for the floodgate player

discord:
  enabled: false
  webhook-url: https://discord.com
  username: "Keklist"
  avatar-url: "https://avatars.githubusercontent.com/u/81553878?s=200&v=4"
  events: ["blacklist_add", "blacklist_remove", "whitelist_add", "whitelist_remove", "limbo", "prelogin_kick"]
  ping-roles: ["214809157574983681"]

# Settings for the database
# This is useful to share the blacklist and whitelist between multiple servers
mariadb:
  enabled: false
  host: localhost
  port: 3306
  database: keklist
  username: root
  password: root
  options: "?useSSL=false&serverTimezone=MEZ"

# Messages for the plugin
# This fully supports minimessage
messages:
  motd:
    blacklisted:
      - "<red><bold>Your IP is blacklisted on this server!"
      - "<red><bold>You are not allowed to join this server!"
    whitelisted:
      - "<gold><bold>The server is in whitelist mode but you can join."
      - "<gold><bold>Glad you can join us!"
    default:
      - "This is a normal motd"
      - "By default these are visible for everyone"

  kick:
    blacklisted:
      - "<red><bold>You're kicked because you're on the blacklist!"
      - "<red><bold>Sorry, but you're not allowed to join this server!"
    whitelisted:
      - "<gold><bold>You're kicked because the server is in whitelist mode!"
      - "<gold><bold>Sorry, but you're not on the whitelist!"

# Enable bstats
# This is used to collect anonymous data about the plugin, which helps me to improve the plugin
bstats: true