blacklist:
  enabled: true
  allow-join-with-admin: false
  admin-permission: "blacklist.admin"
  limbo: false # Experimental
whitelist: true

# Note: If you use a proxy you need to enable 'send-floodgate-data' on the proxy's config
# More: https://wiki.geysermc.org/floodgate/setup/
floodgate:
  prefix: "." # Prefix for the floodgate player

messages:
  motd:
    blacklisted:
      - "<red><bold>Du kek"
      - "Nochmal du kek"
    whitelisted:
      - "Du gut"
      - "Nochmal du gut"
    default:
      - "Du normal"
      - "Du normal aber 2"

  kick:
    blacklisted:
      - "<red><bold>Du kek"
      - "Nochmal du kek"
    whitelisted:
      - "Du gut"
      - "Nochmal du gut"