blacklist:
  enabled: true
  allow-join-with-admin: false
  admin-permission: "blacklist.admin"
  limbo: false # Not supported yet

whitelist: true

messages:
  motd:
    blacklisted:
      - "<red><bold>Du kek"
      - "Nochmal du kek"
    whitelisted:
      - "Du gut"
      - "Nochmal du gut"
    default:
      - "Du normal"
      - "Du normal aber 2"

  kick:
    blacklisted:
      - "<red><bold>Du kek"
      - "Nochmal du kek"
    whitelisted:
      - "Du gut"
      - "Nochmal du gut"