name: Keklist
version: '1.0.0'
main: de.hdg.keklist.Keklist
api-version: '1.19'
description: Custom made white and blacklist with many features!
authors: ["hdgamer1404Jonas", "SageSphinx63920"]
website: https://keklist.pages.dev
loader: de.hdg.keklist.KeklistLoader
dependencies:
  - name: floodgate
    required: false
    bootstrap: false

  - name: Plan
    required: false
    bootstrap: false

  - name: PlaceholderAPI
    required: false
    bootstrap: false

load-after:
  - name: Plan
    bootstrap: false