name: Keklist
version: '1.0.0'
main: de.hdg.keklist.Keklist
api-version: '1.20'
description: Custom made white and blacklist with many features!
authors: [ "hdgamer1404Jonas", "SageSphinx63920" ]
website: https://keklist.pages.dev
loader: de.hdg.keklist.KeklistLoader
dependencies:
  server:
    floodgate:
      load: BEFORE
      required: false

    Plan:
      required: false

    PlaceholderAPI:
      required: false

load-after:
  - name: Plan
    bootstrap: false