name: Keklist
version: '1.0.0'
main: de.hdg.keklist.Keklist
api-version: '1.19'
description: Block all the Keks and accept the nice people
authors: ["hdgamer1404Jonas", "SageSphinx63920"]
website: https://swc.sasp.gq
database: true
dependencies:
  - name: floodgate
    required: false
    bootstrap: false