name: Keklist
version: 1.0.0
main: de.hdg.keklist.Keklist
api-version: 1.20
description: Block all the Keks and accept the nice people
authors: ["hdgamer1404Jonas", "SageSphinx63920"]
website: https://swc.sasp.gq
database: true
softdepend:
  - floodgate

commands:
  whitelist:
    description: Whitelist commands
    usage: /whitelist <add|remove>
    aliases: [wl]
    permission: keklist.whitelist
  blacklist:
    description: Blacklist commands
    usage: /blacklist <add|remove>
    aliases: [bl]
    permission: keklist.blacklist