name: Bug report
description: >-
  Template to report bugs of the plugin (NOT API).
title: '[Bug]: '
assignees:
  - SageSphinx63920
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: >-
        Before reporting a crash or misbehaviour here, please make sure you are using the latest
        version of the plugin! If this doesn’t look right, [choose another form](https://github.com/Simpig-city/Keklist/issues/new/choose)
  - type: input
    id: server
    attributes:
      label: Serve version & software
      description: Which server software do you use and which version of this.
      placeholder: Im running Paper x.x.x
    validations:
      required: true
  - type: input
    id: plugin
    attributes:
      label: Plugin version
      description: Which plugin version do you use?
      placeholder: Keklist v1.0.0-SNAPSHOT
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 'Expected behavior:'
      description: What should the plugin do?
      placeholder: The plugin should...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      description: What actually happened.
      placeholder: The plugin instead does...
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: >-
        This may include a build schematic, a video, or detailed instructions to
        help reconstruct the issue.
      placeholder: 'I used the command xy with xy enabled '
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Agreements
      description: You meet these conditions
      options:
        - label: Im using the latest version of the plugin.
          required: true
        - label: >-
            I have searched for and ensured there isn't already an open issue
            regarding this.
          required: true
        - label: My server is supported by the plugin!
          required: true
  - type: textarea
    id: other
    attributes:
      label: Other
      description: Do you have anything else to include to this issue?
