name: Publish Javadocs
on:
  #push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]
  workflow_dispatch:


jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🙃
      uses: actions/checkout@v4
      
    - name: Set up JDK 21 🛠
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'corretto'
        cache: 'gradle'
        
    - name: Build Javadocs with Gradle ⚙
      run: ./gradlew javadoc
      
    - name: Deploy  🚀
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: javadocs
        publish_dir: ./build/docs/javadoc
