name: Translations
on:
  push:
    paths:
      - 'src/main/resources/assets/lang/en-us.json'
  pull_request:
    paths:
      - 'src/main/resources/assets/lang/en-us.json'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Crowdin Upload
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: false

          source: src/main/resources/assets/lang/en-us.json
          translation: src/main/resources/assets/lang/%locale%.json

          crowdin_branch_name: "${{ env.BRANCH_NAME }}"
          project_id: ${{ vars.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true